dist: bionic
sudo: false

language: node_js
node_js:
  - "10"

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
     - ./node_modules

before_install:
  - export CHROME_BIN=chromium-browser

install:
  - npm install  

env:
  - COMMAND='lint'
  - COMMAND='policy'
  - COMMAND='unit'
  - COMMAND='e2e'
  - COMMAND='build'

script: "npm run ci-tests -- $COMMAND"
